package dev.redengdev.mixins;

import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

import com.hypixel.hytale.builtin.hytalegenerator.assets.propdistribution.GraphPropDistributionAsset;
import com.hypixel.hytale.builtin.hytalegenerator.assets.propdistribution.PropDistributionAsset;
import com.hypixel.hytale.builtin.hytalegenerator.propdistributions.EmptyPropDistribution;
import com.hypixel.hytale.builtin.hytalegenerator.propdistributions.GraphPropDistribution;
import com.hypixel.hytale.builtin.hytalegenerator.propdistributions.PropDistribution;

import dev.redengdev.accessors.GraphPropDistributionAccessor;

@Mixin(GraphPropDistributionAsset.class)
public class GraphPropDistributionAssetMixin {

    @Inject(
        method = "build(Lcom/hypixel/hytale/builtin/hytalegenerator/assets/propdistribution/PropDistributionAsset$Argument;)Lcom/hypixel/hytale/builtin/hytalegenerator/propdistributions/PropDistribution;",
        at = @At("RETURN"),
        cancellable = true
    )
    private void onBuild(PropDistributionAsset.Argument argument, CallbackInfoReturnable<PropDistribution> cir) {
        // 1. Grab the original PropDistribution instance generated by Hytale
        PropDistribution propDistribution = cir.getReturnValue();

        if (propDistribution == EmptyPropDistribution.INSTANCE)
            return;

        if (propDistribution instanceof GraphPropDistribution graphPropDistribution)
        {
            ((GraphPropDistributionAccessor)graphPropDistribution).setMaterialCache(argument.materialCache);
        }
    }
}
